### ISSUE TITLE
Idea 1: Katana Nil -- To-do's

### ISSUE THREAD

**Issue by rear9** [Rear9/Overlimit#1]
- [ ] Scene Design [menu,1,2,3]
- [ ] Audio [Single-file]
- [x] Enemy Model
- [ ] Weapon Model
- [x] Enemy AI [+projectiles]
- [x] Slow motion feature
- [x] Wall-climbing
- [ ] Swinging possibility
- [ ] Weapons [?]
- [ ] Dodge mechanic
- [ ] Collectibles [incentive]

**Concept;**

**Dodge enemy projectiles, jump/swing through levels, collect items/coins to be used to progress to 2nd and 3rd levels,
encouraging exploration and full completion of scenes, player may have a knife/katana and slow-motion for a feature to cut through bullets mid-air, etc etc**
