### ISSUE TITLE
Idea 2: Bleak Streets -- To-do's

### ISSUE THREAD

**Issue by Rear9** [Rear9/Overlimit#2]
- [ ] Audio [Multiple files, blending areas]
- [ ] Level Design [simple 1-scene]
- [ ] Wall-climb
- [ ] Wall-jump polish
- [ ] Wall-run polish
- [ ] Vaults
- [ ] Slides
- [ ] Q 180-mechanic [M-E]
- [ ] Single collectible fab
- [ ] Progress-bar objective

**Concept;**

**The bus will be here in 5 minutes, but the player lost his wallet, he must explore and find money within the level through the use of all movement features implemented, partially linear implementation, focus on smooth movement and optimization/bug-testing**
